# Generated by Django 3.1.3 on 2021-02-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20210221_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PSNamesDuplicate',
        ),
    ]
