# Generated by Django 3.1.3 on 2021-02-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_psnamesduplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localintelligence',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
