# Generated by Django 3.1.3 on 2021-02-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_delete_psnamesduplicate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaldiary',
            old_name='isVerified',
            new_name='verified',
        ),
        migrations.RenameField(
            model_name='localintelligence',
            old_name='detail',
            new_name='details',
        ),
    ]
